### ISSUE TITLE
Infura warning when using Geth

### ISSUE THREAD

**Issue by actuallymentor** [rocket-pool/smartnode-install#10] opened 2020-10-07 09:45 UTC
Durign `rocketpool service config` I selected I want to run Geth. When running `rocketpool service start` for the first time I get the following output:

```
The INFURA_PROJECT_ID variable is not set. Defaulting to a blank string.
Creating network "rocketpool_net" with the default driver
Creating volume "rocketpool_eth1clientdata" with default driver
Creating volume "rocketpool_eth2clientdata" with default driver
Pulling eth1 (ethereum/client-go:v1.9.22)...
.... # THIS RUNS FINE
```

The line `The INFURA_PROJECT_ID variable is not set. Defaulting to a blank string.` seems not to be relevant if I selected Geth.

**Comment by moles1** [comment] 2020-10-08 22:31
Duplicate of https://github.com/rocket-pool/smartnode/issues/56

**Closed by moles1** 2020-10-08 22:31 UTC
